name: Test deployment for release

on:
  push:
    branches:
      - release
jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: JMeter Test
        uses: QAInsights/PerfAction@v2.0
        with:
          test-plan-path: ./jmeterTests/Release_v1_0_0.jmx
          args: ""
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl

